### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by ChrisGoodwinNH** [deleteme/looper.js#5]
[This package](https://www.jsdelivr.com/package/npm/looper.js) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by deleteme** [comment]
Fixed by https://github.com/deleteme/looper.js/commit/f96819b96940eaf2408c18d7f7223da76cb90f7a. This is set in `v3.1.0`. https://www.jsdelivr.com/package/npm/looper.js?version=3.1.0
